### ISSUE TITLE
Mispelling in documentation

### ISSUE THREAD

**Issue by pak11273** [gutenye/transform-imports-react-icons#1]
In the .babelrc you have the plugin "transform-imports".  Shouldn't it be "transform-import"?

**Comment by gutenye** [comment]
@pak11273 Thanks for reporting, `transform-imports` is correct, I misspelled `transform-import` in `yarn add ...`. 
It uses https://www.npmjs.com/package/babel-plugin-transform-imports

Fixed in https://github.com/gutenye/transform-imports-react-icons/commit/1d4ebe33c87a51049a73076a9ba17f742f12c1eb
